//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MobileWx.Web.mobilePay {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mobilePaySoap", Namespace="http://tempuri.org/")]
    public partial class mobilePay : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CFT_pay_99OperationCompleted;
        
        private System.Threading.SendOrPostCallback CFT_payOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PhoneNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback CFT_updateOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductList_CommOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddInvoiceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyPCUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mobilePay() {
            this.Url = global::MobileWx.Web.Properties.Settings.Default.MobileWx_Web_mobilePay_mobilePay;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CFT_pay_99CompletedEventHandler CFT_pay_99Completed;
        
        /// <remarks/>
        public event CFT_payCompletedEventHandler CFT_payCompleted;
        
        /// <remarks/>
        public event Get_PhoneNumCompletedEventHandler Get_PhoneNumCompleted;
        
        /// <remarks/>
        public event CFT_updateOrderCompletedEventHandler CFT_updateOrderCompleted;
        
        /// <remarks/>
        public event GetOrderListCompletedEventHandler GetOrderListCompleted;
        
        /// <remarks/>
        public event GetOrderDetailCompletedEventHandler GetOrderDetailCompleted;
        
        /// <remarks/>
        public event GetProductListCompletedEventHandler GetProductListCompleted;
        
        /// <remarks/>
        public event GetProductList_CommCompletedEventHandler GetProductList_CommCompleted;
        
        /// <remarks/>
        public event AddInvoiceInfoCompletedEventHandler AddInvoiceInfoCompleted;
        
        /// <remarks/>
        public event VerifyPCUserCompletedEventHandler VerifyPCUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CFT_pay_99", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CFT_pay_99(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID, string name) {
            object[] results = this.Invoke("CFT_pay_99", new object[] {
                        orderID,
                        cpNumber,
                        productID,
                        businessesID,
                        payType,
                        personID,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CFT_pay_99Async(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID, string name) {
            this.CFT_pay_99Async(orderID, cpNumber, productID, businessesID, payType, personID, name, null);
        }
        
        /// <remarks/>
        public void CFT_pay_99Async(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID, string name, object userState) {
            if ((this.CFT_pay_99OperationCompleted == null)) {
                this.CFT_pay_99OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCFT_pay_99OperationCompleted);
            }
            this.InvokeAsync("CFT_pay_99", new object[] {
                        orderID,
                        cpNumber,
                        productID,
                        businessesID,
                        payType,
                        personID,
                        name}, this.CFT_pay_99OperationCompleted, userState);
        }
        
        private void OnCFT_pay_99OperationCompleted(object arg) {
            if ((this.CFT_pay_99Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CFT_pay_99Completed(this, new CFT_pay_99CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CFT_pay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CFT_pay(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID) {
            object[] results = this.Invoke("CFT_pay", new object[] {
                        orderID,
                        cpNumber,
                        productID,
                        businessesID,
                        payType,
                        personID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CFT_payAsync(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID) {
            this.CFT_payAsync(orderID, cpNumber, productID, businessesID, payType, personID, null);
        }
        
        /// <remarks/>
        public void CFT_payAsync(string orderID, string cpNumber, int productID, string businessesID, int payType, string personID, object userState) {
            if ((this.CFT_payOperationCompleted == null)) {
                this.CFT_payOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCFT_payOperationCompleted);
            }
            this.InvokeAsync("CFT_pay", new object[] {
                        orderID,
                        cpNumber,
                        productID,
                        businessesID,
                        payType,
                        personID}, this.CFT_payOperationCompleted, userState);
        }
        
        private void OnCFT_payOperationCompleted(object arg) {
            if ((this.CFT_payCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CFT_payCompleted(this, new CFT_payCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_PhoneNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_PhoneNum(string orderID) {
            object[] results = this.Invoke("Get_PhoneNum", new object[] {
                        orderID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_PhoneNumAsync(string orderID) {
            this.Get_PhoneNumAsync(orderID, null);
        }
        
        /// <remarks/>
        public void Get_PhoneNumAsync(string orderID, object userState) {
            if ((this.Get_PhoneNumOperationCompleted == null)) {
                this.Get_PhoneNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PhoneNumOperationCompleted);
            }
            this.InvokeAsync("Get_PhoneNum", new object[] {
                        orderID}, this.Get_PhoneNumOperationCompleted, userState);
        }
        
        private void OnGet_PhoneNumOperationCompleted(object arg) {
            if ((this.Get_PhoneNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PhoneNumCompleted(this, new Get_PhoneNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CFT_updateOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CFT_updateOrder(string OrderID, string payOrderID, int payStatus) {
            object[] results = this.Invoke("CFT_updateOrder", new object[] {
                        OrderID,
                        payOrderID,
                        payStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CFT_updateOrderAsync(string OrderID, string payOrderID, int payStatus) {
            this.CFT_updateOrderAsync(OrderID, payOrderID, payStatus, null);
        }
        
        /// <remarks/>
        public void CFT_updateOrderAsync(string OrderID, string payOrderID, int payStatus, object userState) {
            if ((this.CFT_updateOrderOperationCompleted == null)) {
                this.CFT_updateOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCFT_updateOrderOperationCompleted);
            }
            this.InvokeAsync("CFT_updateOrder", new object[] {
                        OrderID,
                        payOrderID,
                        payStatus}, this.CFT_updateOrderOperationCompleted, userState);
        }
        
        private void OnCFT_updateOrderOperationCompleted(object arg) {
            if ((this.CFT_updateOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CFT_updateOrderCompleted(this, new CFT_updateOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrderList(string phoneNum) {
            object[] results = this.Invoke("GetOrderList", new object[] {
                        phoneNum});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderListAsync(string phoneNum) {
            this.GetOrderListAsync(phoneNum, null);
        }
        
        /// <remarks/>
        public void GetOrderListAsync(string phoneNum, object userState) {
            if ((this.GetOrderListOperationCompleted == null)) {
                this.GetOrderListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderListOperationCompleted);
            }
            this.InvokeAsync("GetOrderList", new object[] {
                        phoneNum}, this.GetOrderListOperationCompleted, userState);
        }
        
        private void OnGetOrderListOperationCompleted(object arg) {
            if ((this.GetOrderListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderListCompleted(this, new GetOrderListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrderDetail(string phoneNum, string orderId) {
            object[] results = this.Invoke("GetOrderDetail", new object[] {
                        phoneNum,
                        orderId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderDetailAsync(string phoneNum, string orderId) {
            this.GetOrderDetailAsync(phoneNum, orderId, null);
        }
        
        /// <remarks/>
        public void GetOrderDetailAsync(string phoneNum, string orderId, object userState) {
            if ((this.GetOrderDetailOperationCompleted == null)) {
                this.GetOrderDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderDetailOperationCompleted);
            }
            this.InvokeAsync("GetOrderDetail", new object[] {
                        phoneNum,
                        orderId}, this.GetOrderDetailOperationCompleted, userState);
        }
        
        private void OnGetOrderDetailOperationCompleted(object arg) {
            if ((this.GetOrderDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderDetailCompleted(this, new GetOrderDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProductList(string phone_Num, int flag, int versionFlag) {
            object[] results = this.Invoke("GetProductList", new object[] {
                        phone_Num,
                        flag,
                        versionFlag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductListAsync(string phone_Num, int flag, int versionFlag) {
            this.GetProductListAsync(phone_Num, flag, versionFlag, null);
        }
        
        /// <remarks/>
        public void GetProductListAsync(string phone_Num, int flag, int versionFlag, object userState) {
            if ((this.GetProductListOperationCompleted == null)) {
                this.GetProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductListOperationCompleted);
            }
            this.InvokeAsync("GetProductList", new object[] {
                        phone_Num,
                        flag,
                        versionFlag}, this.GetProductListOperationCompleted, userState);
        }
        
        private void OnGetProductListOperationCompleted(object arg) {
            if ((this.GetProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductList_Comm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProductList_Comm(string phone_Num, int flag) {
            object[] results = this.Invoke("GetProductList_Comm", new object[] {
                        phone_Num,
                        flag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductList_CommAsync(string phone_Num, int flag) {
            this.GetProductList_CommAsync(phone_Num, flag, null);
        }
        
        /// <remarks/>
        public void GetProductList_CommAsync(string phone_Num, int flag, object userState) {
            if ((this.GetProductList_CommOperationCompleted == null)) {
                this.GetProductList_CommOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductList_CommOperationCompleted);
            }
            this.InvokeAsync("GetProductList_Comm", new object[] {
                        phone_Num,
                        flag}, this.GetProductList_CommOperationCompleted, userState);
        }
        
        private void OnGetProductList_CommOperationCompleted(object arg) {
            if ((this.GetProductList_CommCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductList_CommCompleted(this, new GetProductList_CommCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddInvoiceInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddInvoiceInfo(string phoneNum, string cpNumber_ass, string type, string invoiceHead, string address) {
            object[] results = this.Invoke("AddInvoiceInfo", new object[] {
                        phoneNum,
                        cpNumber_ass,
                        type,
                        invoiceHead,
                        address});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddInvoiceInfoAsync(string phoneNum, string cpNumber_ass, string type, string invoiceHead, string address) {
            this.AddInvoiceInfoAsync(phoneNum, cpNumber_ass, type, invoiceHead, address, null);
        }
        
        /// <remarks/>
        public void AddInvoiceInfoAsync(string phoneNum, string cpNumber_ass, string type, string invoiceHead, string address, object userState) {
            if ((this.AddInvoiceInfoOperationCompleted == null)) {
                this.AddInvoiceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddInvoiceInfoOperationCompleted);
            }
            this.InvokeAsync("AddInvoiceInfo", new object[] {
                        phoneNum,
                        cpNumber_ass,
                        type,
                        invoiceHead,
                        address}, this.AddInvoiceInfoOperationCompleted, userState);
        }
        
        private void OnAddInvoiceInfoOperationCompleted(object arg) {
            if ((this.AddInvoiceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddInvoiceInfoCompleted(this, new AddInvoiceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyPCUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VerifyPCUser(string cpNumber, string PC_UserName, string PC_UserPasswd) {
            object[] results = this.Invoke("VerifyPCUser", new object[] {
                        cpNumber,
                        PC_UserName,
                        PC_UserPasswd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyPCUserAsync(string cpNumber, string PC_UserName, string PC_UserPasswd) {
            this.VerifyPCUserAsync(cpNumber, PC_UserName, PC_UserPasswd, null);
        }
        
        /// <remarks/>
        public void VerifyPCUserAsync(string cpNumber, string PC_UserName, string PC_UserPasswd, object userState) {
            if ((this.VerifyPCUserOperationCompleted == null)) {
                this.VerifyPCUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyPCUserOperationCompleted);
            }
            this.InvokeAsync("VerifyPCUser", new object[] {
                        cpNumber,
                        PC_UserName,
                        PC_UserPasswd}, this.VerifyPCUserOperationCompleted, userState);
        }
        
        private void OnVerifyPCUserOperationCompleted(object arg) {
            if ((this.VerifyPCUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyPCUserCompleted(this, new VerifyPCUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CFT_pay_99CompletedEventHandler(object sender, CFT_pay_99CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CFT_pay_99CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CFT_pay_99CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CFT_payCompletedEventHandler(object sender, CFT_payCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CFT_payCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CFT_payCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void Get_PhoneNumCompletedEventHandler(object sender, Get_PhoneNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PhoneNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PhoneNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CFT_updateOrderCompletedEventHandler(object sender, CFT_updateOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CFT_updateOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CFT_updateOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetOrderListCompletedEventHandler(object sender, GetOrderListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetOrderDetailCompletedEventHandler(object sender, GetOrderDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetProductListCompletedEventHandler(object sender, GetProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetProductList_CommCompletedEventHandler(object sender, GetProductList_CommCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductList_CommCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductList_CommCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AddInvoiceInfoCompletedEventHandler(object sender, AddInvoiceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddInvoiceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddInvoiceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void VerifyPCUserCompletedEventHandler(object sender, VerifyPCUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyPCUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyPCUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591