//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWx.Web.StockSynServiceMob {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockSynServiceMob.MyStockSynServiceMobSoap")]
    public interface MyStockSynServiceMobSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMyStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetMyStock(string uid, string pid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMyStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object AddMyStock(string uid, string stockcode, string pid, string token, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelMyStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object DelMyStock(string uid, string stockcode, string pid, string token, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyStockCover", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object MyStockCover(string uid, string stockcode, string pid, string token, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CopyAndWrite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CopyAndWrite(string UidFrom, string UidTo, string UidOld);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyStockSynServiceMobSoapChannel : MobileWx.Web.StockSynServiceMob.MyStockSynServiceMobSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyStockSynServiceMobSoapClient : System.ServiceModel.ClientBase<MobileWx.Web.StockSynServiceMob.MyStockSynServiceMobSoap>, MobileWx.Web.StockSynServiceMob.MyStockSynServiceMobSoap {
        
        public MyStockSynServiceMobSoapClient() {
        }
        
        public MyStockSynServiceMobSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyStockSynServiceMobSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyStockSynServiceMobSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyStockSynServiceMobSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetMyStock(string uid, string pid, string token) {
            return base.Channel.GetMyStock(uid, pid, token);
        }
        
        public object AddMyStock(string uid, string stockcode, string pid, string token, string group) {
            return base.Channel.AddMyStock(uid, stockcode, pid, token, group);
        }
        
        public object DelMyStock(string uid, string stockcode, string pid, string token, string group) {
            return base.Channel.DelMyStock(uid, stockcode, pid, token, group);
        }
        
        public object MyStockCover(string uid, string stockcode, string pid, string token, string group) {
            return base.Channel.MyStockCover(uid, stockcode, pid, token, group);
        }
        
        public bool CopyAndWrite(string UidFrom, string UidTo, string UidOld) {
            return base.Channel.CopyAndWrite(UidFrom, UidTo, UidOld);
        }
    }
}
