//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.NewsToHTML.NewsServiceWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsServiceWs.INewsToHTML")]
    public interface INewsToHTML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/DoWork", ReplyAction="http://tempuri.org/INewsToHTML/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/CreateHtmlById", ReplyAction="http://tempuri.org/INewsToHTML/CreateHtmlByIdResponse")]
        void CreateHtmlById(int newsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/CreateggHtmlById", ReplyAction="http://tempuri.org/INewsToHTML/CreateggHtmlByIdResponse")]
        void CreateggHtmlById(long newsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/Create2ptPcHtmlById", ReplyAction="http://tempuri.org/INewsToHTML/Create2ptPcHtmlByIdResponse")]
        void Create2ptPcHtmlById(string newsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/CreateById", ReplyAction="http://tempuri.org/INewsToHTML/CreateByIdResponse")]
        void CreateById(string newsId, string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/CreateZdlhHtmlById", ReplyAction="http://tempuri.org/INewsToHTML/CreateZdlhHtmlByIdResponse")]
        void CreateZdlhHtmlById(string newsId, bool rewrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/CreateXfzgHtmlById", ReplyAction="http://tempuri.org/INewsToHTML/CreateXfzgHtmlByIdResponse")]
        void CreateXfzgHtmlById(string newsId, bool rewrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsToHTML/FileCopy", ReplyAction="http://tempuri.org/INewsToHTML/FileCopyResponse")]
        void FileCopy(string filePath, string fileContent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsToHTMLChannel : Mobile.NewsToHTML.NewsServiceWs.INewsToHTML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsToHTMLClient : System.ServiceModel.ClientBase<Mobile.NewsToHTML.NewsServiceWs.INewsToHTML>, Mobile.NewsToHTML.NewsServiceWs.INewsToHTML {
        
        public NewsToHTMLClient() {
        }
        
        public NewsToHTMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsToHTMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsToHTMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsToHTMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void CreateHtmlById(int newsId) {
            base.Channel.CreateHtmlById(newsId);
        }
        
        public void CreateggHtmlById(long newsId) {
            base.Channel.CreateggHtmlById(newsId);
        }
        
        public void Create2ptPcHtmlById(string newsId) {
            base.Channel.Create2ptPcHtmlById(newsId);
        }
        
        public void CreateById(string newsId, string s) {
            base.Channel.CreateById(newsId, s);
        }
        
        public void CreateZdlhHtmlById(string newsId, bool rewrite) {
            base.Channel.CreateZdlhHtmlById(newsId, rewrite);
        }
        
        public void CreateXfzgHtmlById(string newsId, bool rewrite) {
            base.Channel.CreateXfzgHtmlById(newsId, rewrite);
        }
        
        public void FileCopy(string filePath, string fileContent) {
            base.Channel.FileCopy(filePath, fileContent);
        }
    }
}
